import { Prisma } from '@prisma/client';

export const phase1WorkoutPlans: Prisma.WorkoutPlanCreateInput[] = [
    {
        id: 'p1w1d1',
        user: { connect: { id: 'user1' } },
        name: 'Lower Body Foundation',
        description: 'Build foundational lower body strength and jump power',
        phase: 1,
        week: 1,
        day: 1,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Lower Strength',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex3' } }, orderIndex: 1, sets: 3, reps: '8-10', restSeconds: 90 },
            { exercise: { connect: { id: 'ex4' } }, orderIndex: 2, sets: 4, reps: '5', restSeconds: 120 },
            { exercise: { connect: { id: 'ex5' } }, orderIndex: 3, sets: 3, reps: '10/side', restSeconds: 90 },
          ],
        },
      },
      {
        id: 'p1w1d2',
        user: { connect: { id: 'user1' } },
        name: 'HIIT Endurance',
        description: 'High-intensity interval training for match endurance',
        phase: 1,
        week: 1,
        day: 2,
        estimatedDuration: 45,
        difficulty: 'HIGH',
        focus: 'Endurance',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex8' } }, orderIndex: 1, sets: 10, reps: '30s sprint / 90s rest', restSeconds: 90 },
          ],
        },
      },
      {
        id: 'p1w1d3',
        user: { connect: { id: 'user1' } },
        name: 'Upper Body Power',
        description: 'Explosive upper body strength for throwing and defense',
        phase: 1,
        week: 1,
        day: 3,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Upper Power',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex1' } }, orderIndex: 1, sets: 4, reps: '8-10', restSeconds: 90 },
            { exercise: { connect: { id: 'ex6' } }, orderIndex: 2, sets: 4, reps: '8', restSeconds: 90 },
            { exercise: { connect: { id: 'ex7' } }, orderIndex: 3, sets: 3, reps: 'max', restSeconds: 120 },
          ],
        },
      },
      {
        id: 'p1w1d4',
        user: { connect: { id: 'user1' } },
        name: 'Mobility and Recovery',
        description: 'Improve joint health and flexibility',
        phase: 1,
        week: 1,
        day: 4,
        estimatedDuration: 30,
        difficulty: 'LOW',
        focus: 'Mobility',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex10' } }, orderIndex: 1, sets: 2, reps: '10/side', restSeconds: 30 },
            { exercise: { connect: { id: 'ex12' } }, orderIndex: 2, sets: 1, reps: '1 flow', restSeconds: 0 },
          ],
        },
      },
      {
        id: 'p1w1d5',
        user: { connect: { id: 'user1' } },
        name: 'Full-Body Power and Agility',
        description: 'Develop explosive power and lateral movement',
        phase: 1,
        week: 1,
        day: 5,
        estimatedDuration: 60,
        difficulty: 'HIGH',
        focus: 'Full-Body Power',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex4' } }, orderIndex: 1, sets: 4, reps: '5', restSeconds: 120 },
            { exercise: { connect: { id: 'ex9' } }, orderIndex: 2, sets: 4, reps: '10/side', restSeconds: 90 },
            { exercise: { connect: { id: 'ex11' } }, orderIndex: 3, sets: 3, reps: '10/side', restSeconds: 60 },
          ],
        },
      },
      {
        id: 'p1w1d6',
        user: { connect: { id: 'user1' } },
        name: 'Aerobic Base',
        description: 'Steady-state running to build endurance',
        phase: 1,
        week: 1,
        day: 6,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Endurance',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex8' } }, orderIndex: 1, sets: 1, reps: '45min tempo run', restSeconds: 0 },
          ],
        },
      },
    
      // Phase 1 - Week 2 (progression example)
      {
        id: 'p1w2d1',
        user: { connect: { id: 'user1' } },
        name: 'Lower Body Progressive',
        description: 'Increase volume and load for strength progression',
        phase: 1,
        week: 2,
        day: 1,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Lower Strength',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex3' } }, orderIndex: 1, sets: 4, reps: '8-10', restSeconds: 90 },
            { exercise: { connect: { id: 'ex4' } }, orderIndex: 2, sets: 4, reps: '5', restSeconds: 120 },
            { exercise: { connect: { id: 'ex5' } }, orderIndex: 3, sets: 3, reps: '10/side', restSeconds: 90 },
          ],
        },
      },
      {
        id: 'p1w2d2',
        user: { connect: { id: 'user1' } },
        name: 'HIIT Endurance',
        description: 'Maintain high-intensity interval training',
        phase: 1,
        week: 2,
        day: 2,
        estimatedDuration: 45,
        difficulty: 'HIGH',
        focus: 'Endurance',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex8' } }, orderIndex: 1, sets: 12, reps: '30s sprint / 90s rest', restSeconds: 90 },
          ],
        },
      },
      {
        id: 'p1w2d3',
        user: { connect: { id: 'user1' } },
        name: 'Upper Body Power',
        description: 'Continue upper body explosive strength work',
        phase: 1,
        week: 2,
        day: 3,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Upper Power',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex1' } }, orderIndex: 1, sets: 4, reps: '8-10', restSeconds: 90 },
            { exercise: { connect: { id: 'ex6' } }, orderIndex: 2, sets: 4, reps: '8', restSeconds: 90 },
            { exercise: { connect: { id: 'ex7' } }, orderIndex: 3, sets: 4, reps: 'max', restSeconds: 120 },
          ],
        },
      },
      {
        id: 'p1w2d4',
        user: { connect: { id: 'user1' } },
        name: 'Mobility and Recovery',
        description: 'Maintain joint health and flexibility',
        phase: 1,
        week: 2,
        day: 4,
        estimatedDuration: 30,
        difficulty: 'LOW',
        focus: 'Mobility',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex10' } }, orderIndex: 1, sets: 2, reps: '10/side', restSeconds: 30 },
            { exercise: { connect: { id: 'ex12' } }, orderIndex: 2, sets: 1, reps: '1 flow', restSeconds: 0 },
          ],
        },
      },
      {
        id: 'p1w2d5',
        user: { connect: { id: 'user1' } },
        name: 'Full-Body Power and Agility',
        description: 'Power and lateral movement progression',
        phase: 1,
        week: 2,
        day: 5,
        estimatedDuration: 60,
        difficulty: 'HIGH',
        focus: 'Full-Body Power',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex4' } }, orderIndex: 1, sets: 4, reps: '5', restSeconds: 120 },
            { exercise: { connect: { id: 'ex9' } }, orderIndex: 2, sets: 4, reps: '10/side', restSeconds: 90 },
            { exercise: { connect: { id: 'ex11' } }, orderIndex: 3, sets: 4, reps: '10/side', restSeconds: 60 },
          ],
        },
      },
      {
        id: 'p1w2d6',
        user: { connect: { id: 'user1' } },
        name: 'Aerobic Base',
        description: 'Steady-state running to build endurance',
        phase: 1,
        week: 2,
        day: 6,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Endurance',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex8' } }, orderIndex: 1, sets: 1, reps: '50min tempo run', restSeconds: 0 },
          ],
        },
      },
    
      // Phase 1 - Week 3 (similar progression)
      {
        id: 'p1w3d1',
        user: { connect: { id: 'user1' } },
        name: 'Lower Body Strength Peak',
        description: 'Peak volume and intensity for lower body',
        phase: 1,
        week: 3,
        day: 1,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Lower Strength',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex3' } }, orderIndex: 1, sets: 4, reps: '10-12', restSeconds: 90 },
            { exercise: { connect: { id: 'ex4' } }, orderIndex: 2, sets: 5, reps: '6', restSeconds: 120 },
            { exercise: { connect: { id: 'ex5' } }, orderIndex: 3, sets: 4, reps: '12/side', restSeconds: 90 },
          ],
        },
      },
      {
        id: 'p1w3d2',
        user: { connect: { id: 'user1' } },
        name: 'HIIT Endurance Peak',
        description: 'Max effort intervals',
        phase: 1,
        week: 3,
        day: 2,
        estimatedDuration: 45,
        difficulty: 'HIGH',
        focus: 'Endurance',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex8' } }, orderIndex: 1, sets: 14, reps: '30s sprint / 90s rest', restSeconds: 90 },
          ],
        },
      },
      {
        id: 'p1w3d3',
        user: { connect: { id: 'user1' } },
        name: 'Upper Body Power Peak',
        description: 'Max strength and power for upper body',
        phase: 1,
        week: 3,
        day: 3,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Upper Power',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex1' } }, orderIndex: 1, sets: 5, reps: '8-10', restSeconds: 90 },
            { exercise: { connect: { id: 'ex6' } }, orderIndex: 2, sets: 5, reps: '8', restSeconds: 90 },
            { exercise: { connect: { id: 'ex7' } }, orderIndex: 3, sets: 5, reps: 'max', restSeconds: 120 },
          ],
        },
      },
      {
        id: 'p1w3d4',
        user: { connect: { id: 'user1' } },
        name: 'Mobility and Recovery',
        description: 'Maintain flexibility and joint health',
        phase: 1,
        week: 3,
        day: 4,
        estimatedDuration: 30,
        difficulty: 'LOW',
        focus: 'Mobility',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex10' } }, orderIndex: 1, sets: 2, reps: '10/side', restSeconds: 30 },
            { exercise: { connect: { id: 'ex12' } }, orderIndex: 2, sets: 1, reps: '1 flow', restSeconds: 0 },
          ],
        },
      },
      {
        id: 'p1w3d5',
        user: { connect: { id: 'user1' } },
        name: 'Full-Body Power and Agility Peak',
        description: 'Maximal power and agility',
        phase: 1,
        week: 3,
        day: 5,
        estimatedDuration: 60,
        difficulty: 'HIGH',
        focus: 'Full-Body Power',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex4' } }, orderIndex: 1, sets: 5, reps: '6', restSeconds: 120 },
            { exercise: { connect: { id: 'ex9' } }, orderIndex: 2, sets: 5, reps: '12/side', restSeconds: 90 },
            { exercise: { connect: { id: 'ex11' } }, orderIndex: 3, sets: 4, reps: '12/side', restSeconds: 60 },
          ],
        },
      },
      {
        id: 'p1w3d6',
        user: { connect: { id: 'user1' } },
        name: 'Aerobic Base Peak',
        description: 'Longest steady-state run',
        phase: 1,
        week: 3,
        day: 6,
        estimatedDuration: 60,
        difficulty: 'MEDIUM',
        focus: 'Endurance',
        exercises: {
          create: [
            { exercise: { connect: { id: 'ex8' } }, orderIndex: 1, sets: 1, reps: '60min tempo run', restSeconds: 0 },
          ],
        },
      },
];
